README.md
docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md
docs/index.md

Updated UserGuide.md based on the draft UG (Fix #5)

Update UG from draft UG

---

.gitignore
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Birthday.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedBirthday.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/BirthdayTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

There are some things I (or we, as we will encounter it more and more), have to figure out.
The main problem is how do we conditionally render a field, when there is no value there. Would love suggestions.
Closes #22

Add birthday field

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/HelpWindow.css

Update UI to look like UI mockup

---

build.gradle

small bug in #92. Required to run source code through gradle.

fix small bug in build.gradle after refactoring

---

build.gradle

Changes `mainClassName` to `seedu.connectus.Main` to match our current name.
Closes #94 .

Update gradle script

---

src/main/java/seedu/connectus/logic/parser/AddCommandParser.java
src/main/java/seedu/connectus/logic/parser/CliSyntax.java
src/main/java/seedu/connectus/logic/parser/EditCommandParser.java
src/main/java/seedu/connectus/logic/parser/ParserUtil.java
src/main/java/seedu/connectus/model/socialmedia/Telegram.java
src/test/java/seedu/connectus/logic/parser/ParserUtilTest.java

...and support respective social media parsing error message.
Should close #82 #87 .

Deprecate "sm/" prefix

---

src/main/java/seedu/connectus/commons/core/Messages.java
src/main/java/seedu/connectus/logic/commands/AddTagToPersonCommand.java
src/main/java/seedu/connectus/logic/commands/CommandUtil.java
src/main/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommand.java
src/main/java/seedu/connectus/logic/parser/AddTagToPersonCommandParser.java
src/main/java/seedu/connectus/logic/parser/ConnectUsParser.java
src/main/java/seedu/connectus/logic/parser/DeleteTagFromPersonCommandParser.java
src/main/java/seedu/connectus/model/person/Person.java
src/main/java/seedu/connectus/model/tag/Tag.java
src/test/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommandTest.java
src/test/java/seedu/connectus/logic/parser/AddTagToPersonCommandParserTest.java
src/test/java/seedu/connectus/logic/parser/DeleteTagFromPersonCommandParserTest.java

Support tag/module add/delete operations

---

docs/UserGuide.md

UG bug fix

---

src/main/java/seedu/connectus/MainApp.java
src/main/java/seedu/connectus/commons/core/Messages.java
src/main/java/seedu/connectus/logic/commands/HelpCommand.java
src/main/java/seedu/connectus/logic/parser/HelpCommandParser.java
src/test/java/seedu/connectus/logic/commands/HelpCommandTest.java
src/test/java/seedu/connectus/logic/parser/HelpCommandParserTest.java

Added help command feedback so users know that the help command executed successfully

Add help command feedback

---

src/main/java/seedu/connectus/logic/commands/AddTagToPersonCommand.java
src/main/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommand.java
src/main/java/seedu/connectus/logic/parser/AddTagToPersonCommandParser.java
src/main/java/seedu/connectus/logic/parser/DeleteTagFromPersonCommandParser.java
src/main/java/seedu/connectus/model/person/Person.java
src/test/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommandTest.java
src/test/java/seedu/connectus/logic/parser/AddTagToPersonCommandParserTest.java
src/test/java/seedu/connectus/logic/parser/DeleteTagFromPersonCommandParserTest.java

...support CCA and CCA Position

Update `addt`/`deletet` to

---

src/test/java/seedu/connectus/logic/commands/CommandTestUtil.java
src/test/java/seedu/connectus/logic/parser/HelpCommandParserTest.java

#133 has failing tests that will be fixed by this PR

Fix help functionality

---

src/main/java/seedu/connectus/logic/commands/AddCommand.java
src/main/java/seedu/connectus/model/tag/Cca.java
src/main/java/seedu/connectus/model/tag/CcaPosition.java
src/main/java/seedu/connectus/model/tag/Tag.java
src/main/java/seedu/connectus/storage/JsonAdaptedCca.java
src/main/java/seedu/connectus/ui/PersonCard.java
src/test/java/seedu/connectus/model/tag/TagTest.java

couple cca and ccaPosition

---

docs/UserGuide.md

prefixes were all in quotations previously. only the first sentence should be in quotation.

fix UG style for prefix section

---

src/main/java/seedu/connectus/commons/core/Messages.java
src/main/java/seedu/connectus/logic/LogicManager.java
src/main/java/seedu/connectus/logic/commands/UpcomingBirthdayCommand.java
src/main/java/seedu/connectus/logic/parser/ConnectUsParser.java
src/main/java/seedu/connectus/model/person/Birthday.java
src/main/java/seedu/connectus/model/person/RecentBirthdayPredicate.java
src/test/java/seedu/connectus/model/person/BirthdayTest.java

Uses `upcoming-b` to show people with birthday coming.

Show recent birthdays

---

src/main/java/seedu/connectus/commons/core/Messages.java
src/main/java/seedu/connectus/logic/commands/AddCommand.java
src/main/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommand.java
src/test/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommandTest.java

Fix typo in exception message

---

docs/UserGuide.md
src/main/java/seedu/connectus/logic/parser/AddTagToPersonCommandParser.java

Fixes #187, #186, #184, #179, #178

fix documentation bugs

---

src/main/java/seedu/connectus/commons/core/Messages.java
src/main/java/seedu/connectus/logic/parser/ConnectUsParser.java
src/test/java/seedu/connectus/logic/parser/ConnectUsParserTest.java

Fix whitespace input error message

---

src/main/java/seedu/connectus/logic/commands/AddCommand.java
src/main/java/seedu/connectus/logic/commands/AddTagToPersonCommand.java
src/main/java/seedu/connectus/logic/parser/EditCommandParser.java

Fix invalid example add command

---

src/main/java/seedu/connectus/model/tag/Cca.java

add single char cca

---

src/main/java/seedu/connectus/ui/CommandBox.java
src/main/java/seedu/connectus/ui/MainWindow.java

fix bug caused by uncaught error

---

docs/UserGuide.md

...to pre-filled message
Closes #194

Revert `chat` description

---

src/main/java/seedu/connectus/logic/parser/AddTagToPersonCommandParser.java

...so that it checks for constraints
Closes #182

Use `ParserUtils` for tags

---

src/main/java/seedu/connectus/model/person/Person.java
src/main/java/seedu/connectus/model/socialmedia/SocialMedia.java

fix bug in search where 'instagram', 'telegram' and 'whatsapp' are considered part of contact by search

---

src/main/java/seedu/connectus/model/person/Birthday.java
src/test/java/seedu/connectus/logic/commands/UpcomingBirthdayTest.java
src/test/java/seedu/connectus/model/person/BirthdayTest.java

Prevent future dates in birthday

---

docs/UserGuide.md
src/main/java/seedu/connectus/logic/commands/DeleteTagFromPersonCommand.java

delete-t - minor bug fix

---

docs/DeveloperGuide.md
docs/UserGuide.md

Also fixes a notation bug i found in the UG.

Manual Testing Instructions

---

docs/DeveloperGuide.md

I forgot to update the numbering and toc in the DG after adding instructions for testing

Fix numbering and links in DG

---

src/main/java/seedu/connectus/storage/JsonAdaptedPerson.java

minor storage bug fix
